5_MusicPlayer/Group5_MusicPlayer/Controllers/SongsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group5_MusicPlayer.Data;
using Group5_MusicPlayer.Models;
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Http;

namespace Group5_MusicPlayer.Controllers
{
    public class SongsController : Controller
    {
        private readonly MusicPlayerDbContext _context;
        private readonly IHubContext<SignalrServer> _signalRHub;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment Environment;
        public SongsController(MusicPlayerDbContext context, IHubContext<SignalrServer> signalRHub, Microsoft.AspNetCore.Hosting.IHostingEnvironment _Environment)
        {
            _context = context;
            _signalRHub = signalRHub;
            Environment = _Environment;
        }

        // GET: Songs
        public async Task<IActionResult> Index(string? search)
        {
            int userId = int.Parse(HttpContext.Session.GetString("ID"));
            if (userId == 3)
            {
                var musicPlayerAdmin = _context.Songs.Include(s => s.Author).Include(s => s.Category);
                if (!string.IsNullOrEmpty(search))
                {
                    var searchList = _context.Songs.Include(s => s.Author).Include(s => s.Category)
                        .Where(s => s.IsPrivate == false && s.Title.ToLower().Contains(search.ToLower()));
                    ViewBag.query = search;
                    return View(searchList.ToList());
                }
                return View(await musicPlayerAdmin.ToListAsync());
            }
            else if (userId != 3)
            {
                var musicPlayerUser = _context.Songs.Include(s => s.Author).Include(s => s.Category).Where(s => s.AuthorId == userId);
                return View(await musicPlayerUser.ToListAsync());
            }
            return RedirectToAction("Index", "Home");

        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Songs == null)
            {               
                return NotFound();
            }
            var song = await _context.Songs
                .Include(s => s.Author)
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.SongId == id);
            if (song == null)
            {
                song = await _context.Songs
                .Include(s => s.Author)
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.SongId == 5);
            }

            return View(song);
        }

        public IActionResult UploadFile(List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;
            string path = Path.Combine(this.Environment.WebRootPath, "Upload");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            List<string> uploadFiles = new List<string>();
            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadFiles.Add(fileName);
                }
                Console.WriteLine("fileName:", fileName, path);
            }
            return RedirectToPage("/Create"); ;
        }
        // GET: Songs/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserName");
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SongId,Title,CategoryId,AuthorId,ImgPath,AudioPath,IsPrivate")] Song song, List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;
            string path = Path.Combine(this.Environment.WebRootPath, "Upload");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            List<string> uploadFiles = new List<string>();
            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadFiles.Add(fileName);
                }
                Console.WriteLine("fileName:", fileName, path);
                song.AudioPath = fileName;
            }
            if (song.AuthorId == 0)
            {
                int userId = int.Parse(HttpContext.Session.GetString("ID"));
                song.AuthorId = userId;
            }
            _context.Add(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var song = await _context.Songs.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "UserId", "UserName", song.AuthorId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", song.CategoryId);
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("SongId,Title,CategoryId,AuthorId,ImgPath,AudioPath,IsPrivate")] Song song, List<IFormFile> postedFiles)
        {

            string wwwPath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;
            string path = Path.Combine(this.Environment.WebRootPath, "Upload");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            List<string> uploadFiles = new List<string>();
            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadFiles.Add(fileName);
                }
                Console.WriteLine("fileName:", fileName, path);
                song.AudioPath = fileName;
            }
            if (song.AuthorId == 0)
            {
                int userId = int.Parse(HttpContext.Session.GetString("ID"));
                song.AuthorId = userId;
            }
            _context.Update(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var song = await _context.Songs
                .Include(s => s.Author)
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.SongId == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Songs == null)
            {
                return Problem("Entity set 'MusicPlayerDbContext.Songs'  is null.");
            }
            Song song = await _context.Songs.Include(s => s.SongLists).FirstOrDefaultAsync(s => s.SongId == id);

            if (song != null)
            {
                if (song.SongLists.Count > 0)
                {
                    foreach (SongList songList in song.SongLists)
                    {
                        songList.SongId = 5;
                    }
                }
                _context.Songs.Remove(song);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongExists(int id)
        {
            return (_context.Songs?.Any(e => e.SongId == id)).GetValueOrDefault();
        }
    }
}

5_MusicPlayer/Group5_MusicPlayer/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group5_MusicPlayer.Data;
using Group5_MusicPlayer.Models;
using Microsoft.AspNetCore.SignalR;

namespace Group5_MusicPlayer.Controllers
{
    public class UsersController : Controller
    {
        private readonly MusicPlayerDbContext _context;
        private readonly IHubContext<SignalrServer> _signalRHub;

        public UsersController(MusicPlayerDbContext context, IHubContext<SignalrServer> signalRHub)
        {
            _context = context;
            _signalRHub = signalRHub;
        }

        // GET: Users
        public async Task<IActionResult> Index(string? search)
        {
            var account = HttpContext.Session.GetString("Account");
            if (account != "Admin")
                return RedirectToAction("Index", "Home");
            if (!string.IsNullOrEmpty(search))
            {
                var searchList = _context.Users
                    .Where(s => s.UserName.ToLower().Contains(search.ToLower()));
                ViewBag.query = search;
                return View(searchList.ToList());
            }
            return _context.Users != null ?
                        View(await _context.Users.ToListAsync()) :
                        Problem("Entity set 'MusicPlayerDbContext.Users'  is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,Email,Password,Phone,Role")] User user)
        {
            User emailCheck = _context.Users.FirstOrDefault(u => u.Email.ToLower().Equals(user.Email.ToLower()));
            if (emailCheck != null)
            {
                ViewBag.error = "Oops! Email has been taken! Contact admin for information!";
                return View();
            }
            // Save the user to the database
            _context.Add(user);
            await _context.SaveChangesAsync();

            // Create a playlist for the user
            Playlist playlist = new Playlist()
            {
                Title = "Personal Playlist",
                UserId = user.UserId
            };
            _context.Add(playlist);
            await _context.SaveChangesAsync();

            // Redirect to the Index action
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("UserId,UserName,Email,Password,Phone,Role")] User user)
        {
            User emailCheck = _context.Users.FirstOrDefault(u => u.Email.ToLower().Equals(user.Email.ToLower()) && u.UserId != user.UserId);
            if (emailCheck != null)
            {
                ViewBag.error = "Oops! Email has been taken! Contact admin for information!";
                return View();
            }
            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.UserId))
                {
                    return NotFound();
                }
                else
                {
                    return NotFound();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'MusicPlayerDbContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

5_MusicPlayer/Group5_MusicPlayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Group5_MusicPlayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Group5_MusicPlayer.styles.css" asp-append-version="true" />
</head>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Group5_MusicPlayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="width: 80%">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            var Account = HttpContextAccessor.HttpContext.Session.GetString("Account");
                            if (Account != null)
                            {
                                if (Account.Equals("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Users">User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Songs">Song</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Categories">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="Logout" asp-controller="Authorization">Log Out</a>
                                    </li>
                                }
                                else if (Account.Equals("User"))
                                {
                                    var UserID = HttpContextAccessor.HttpContext.Session.GetString("ID");
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="UserPlaylistDetails" asp-controller="Playlists" asp-route-userid="@UserID">To My Playlist</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Songs">My Songs</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="Details" asp-controller="Users" asp-route-id="@UserID">User Information</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-action="Logout" asp-controller="Authorization">Log Out</a>
                                    </li>
                                }
                            }
                            else
                            {
                                <li class="nav-item" style="justify-self:end">
                                    <a class="nav-link text-dark" asp-action="Login" asp-controller="Authorization">Log In</a>
                                </li>
                                <li class="nav-item" style="">
                                    <a class="nav-link text-dark" asp-action="Register" asp-controller="Authorization">Register</a>
                                </li>
                            }
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Group5_MusicPlayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>